---
# tasks file for rhel-patching-pre-tasks

- name: Running RHEL Upgrade Pre-Tasks 
  debug:
    msg: "Backup config and snapshots"

# follow tasks for snapshots and backups as needed

- name: Get Service Facts
  service_facts:

- name: "Check Service List Status"
  debug:
    var: ansible_facts.services["{{ item }}"].state
  with_items: "{{ service_list }}"

- name: "Set Service Status Fact"
  set_fact:
    any_service_running: true
  when: ansible_facts.services["{{ item }}"].state == "running"
  with_items: "{{ service_list }}"

- name: "Some listed services still running. Do you want to continue patching ?"
  pause:
    prompt: Please confirm you want to continue patching. Press return to continue. Press Ctrl+c and then "a" to abort
  when: any_service_running

- name: Backup configuration files
  debug:
    msg: "Taking backup of /etc/fstab, /etc/passwd"

- name: Initiating Snapshot
  debug:
    msg: "Calling Snapshot job"    